# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{textile_toolbar}
  s.version = "0.5.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew Bass"]
  s.date = %q{2013-02-08}
  s.description = %q{Adds a handy Textile toolbar to any text area.}
  s.email = %q{pelargir@gmail.com}
  s.extra_rdoc_files = [
    "README",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "VERSION",
     "files/public/images/textile_toolbar/bold.png",
     "files/public/images/textile_toolbar/hyperlink.png",
     "files/public/images/textile_toolbar/image.png",
     "files/public/images/textile_toolbar/italic.png",
     "files/public/images/textile_toolbar/underline.png",
     "files/public/javascripts/textile_toolbar.js",
     "init.rb",
     "lib/textile_toolbar.rb",
     "tasks/textile_toolbar.rake",
     "test/test_helper.rb",
     "test/textile_toolbar_test.rb",
     "textile_toolbar.gemspec"
  ]
  s.homepage = %q{http://github.com/pelargir/textile_toolbar}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Adds a handy Textile toolbar to any text area.}
  s.test_files = [
    "test/test_helper.rb",
     "test/textile_toolbar_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

